_wandb:
    value:
        cli_version: 0.23.1
        e:
            ngdn4t21740w5ks9wx07lo0pz1x6ycfj:
                args:
                    - --lr
                    - "0.0001"
                    - --batch_size
                    - "100"
                    - --epochs
                    - "10"
                codePath: main_finetune.py
                codePathLocal: main_finetune.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "493310590976"
                        used: "397076201472"
                email: aczern4@gmail.com
                executable: /home/gray/miniconda3/envs/pi-img/bin/python
                git:
                    commit: 59941426139ce0e1188e2da804c1c83330b2f3ac
                    remote: git@github.com:GrayMan124/Master-Thesis.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-6d1a976b-f8b3-3e7a-7f70-1505c3a3063a
                host: Grayjaro
                memory:
                    total: "33459732480"
                os: Linux-6.12.64-1-MANJARO-x86_64-with-glibc2.42
                program: /home/gray/work/Master-Thesis/main_finetune.py
                python: CPython 3.9.21
                root: /home/gray/work/Master-Thesis
                startedAt: "2026-02-02T18:34:32.676814Z"
                writerId: ngdn4t21740w5ks9wx07lo0pz1x6ycfj
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 41
                - 49
                - 51
                - 53
            "3":
                - 13
                - 16
                - 61
            "4": 3.9.21
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
aug:
    value: 0
aug_type:
    value: all
batch_size:
    value: 100
bw:
    value: cv2
config:
    value: null
cores:
    value: 8
data_path:
    value: /mnt/sam/pi_data/processed_data/tinyImageNet/
epochs:
    value: 10
freeze_weights:
    value: false
hidden_size:
    value: 256
lr:
    value: 0.0001
model:
    value: TBR
name:
    value: ""
num_workers:
    value: 2
res:
    value: 100
seed:
    value: 119
sm:
    value: false
tb_add_t:
    value: false
tb_add_x:
    value: false
tbs:
    value: normal
topodim:
    value: 1
topodim_concat:
    value: false
tv:
    value: land
val_size:
    value: 0.2
